//
// (C) 2012 株式会社ジャストシステム
//
// ***** DO NOT EDIT THIS FILE *****

var markerLatitudes = [];
var markerLongitudes = [];
var markerWindowInfoList = [];
var markerWindowOpenFlags = [];
var markerEventNames = [];
var isFirstShownList = [];

// Backward-compatible aliases for legacy generated scripts.
var lat = markerLatitudes;
var lng = markerLongitudes;
var markerwindowinfo = markerWindowInfoList;
var markerwindowopen = markerWindowOpenFlags;
var markerevent = markerEventNames;
var firstshown = isFirstShownList;

function createMarker(mapInstance, markerPosition, markerEventName, infoContentHtml, shouldOpenInfoWindow) {
  var mapMarker = new google.maps.Marker({
    position: markerPosition,
    map: mapInstance
  });
  if (shouldOpenInfoWindow === 1) {
    var infoWindow = new google.maps.InfoWindow({
      content: infoContentHtml
    });
    google.maps.event.addListener(mapMarker, markerEventName, function() {
      infoWindow.open(mapInstance, mapMarker);
    });
  }
  return mapMarker;
}

function hpbmaponload() {
  var mapElement = document.getElementById("HPBMAP_20150611082602");
  var mapOptions = {
    zoom: 16,
    center: new google.maps.LatLng(38.303920, 140.339429),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  return new google.maps.Map(mapElement, mapOptions);
}
